
DASHBOARD_CHANNELS_LINE = 0
DASHBOARD_LAST_SYNC_BYTE = DASHBOARD_CHANNELS_LINE + 1
DASHBOARD_LAST_PAYLOAD_LENGTH = DASHBOARD_CHANNELS_LINE + 2
DASHBOARD_LAST_FRAME_TYPE = DASHBOARD_CHANNELS_LINE + 3
DASHBOARD_TOTAL_FRAMES = DASHBOARD_CHANNELS_LINE + 4
DASHBOARD_TOTAL_ITERATIONS = DASHBOARD_CHANNELS_LINE + 5

DASHBOARD_WARNING = DASHBOARD_LAST_FRAME_TYPE + 5
